# This workflow configures the user-statistician with the
# dark-dimmed color theme, but otherwise uses all of
# the defaults. It is configured on a daily schedule at 3am.
# Reference: <https://github.com/cicirello/user-statistician/tree/main/quickstart>

name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/dark-dimmed.yml' ]
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        colors: dark-dimmed
        max-languages: 5
      env:
        GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
